name: Backend Tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Prepare dependency manager
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv || true

      - name: Install project
        run: |
          if command -v uv >/dev/null 2>&1; then
            uv pip install --system .[dev]
          else
            pip install .[dev]
          fi

      - name: Run pytest
        run: pytest

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: coverage.xml
          if-no-files-found: error
