name: Frontend Tests

on:
  push:
  pull_request:

jobs:
  setup:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  lint_build_test:
    name: Lint, build and test
    runs-on: ubuntu-latest
    needs: setup
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test:ci

      - name: Upload coverage
        if: always() && hashFiles('src/frontend/coverage/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: src/frontend/coverage
          if-no-files-found: ignore
