name: Guards

on:
  push:
  pull_request:

jobs:
  guards:
    runs-on: ubuntu-latest
    env:
      ROADMAP_STEP_PATH: ${{ vars.ROADMAP_STEP_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Inject roadmap reference (auto-detect)
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if ($env:ROADMAP_STEP_PATH) {
            ./tools/guards/ensure_roadmap_ref.ps1 -StepPath $env:ROADMAP_STEP_PATH
          } else {
            ./tools/guards/ensure_roadmap_ref.ps1
          }

      - name: Run guards
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./tools/guards/run_all_guards.ps1
