name: Documentation Guards

on:
  push:
  pull_request:

jobs:
  guards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run guards
        shell: pwsh
        run: |
          ./tools/guards/run_all_guards.ps1

